export const passages = [
    "Live as if you were living already for the second time",
    "When we are no longer able to change a situation, we are challenged to change ourselves",
    "Each man is questioned by life",
    "Suffering is not necessary to find meaning",
    "Fear makes come true that which one is afraid of",
    "Man does not simply exist",
    "Life is never made unbearable by circumstances",
    "The last of human freedoms is to choose one's attitude",
    "When we are no longer able to change a situation",
    "Love is the only way to grasp another human being",
    "Everything can be taken from a man but one thing",
    "Those who have a 'why' to live can bear almost any 'how'",
    "An abnormal reaction to an abnormal situation is normal behavior",
    "What is to give light must endure burning",
    "Ultimately, man should not ask what the meaning of his life is",
    "Each man is questioned by life, and he can only answer with his own life",
    "In some ways suffering ceases to be suffering at the moment it finds a meaning",
    "Everything can be taken but one thing: freedom",
    "He who has a why can bear almost any how",
    "What is to give light must endure burning",
    "Life ultimately means taking responsibility",
    "Love is the ultimate and highest goal",
    "The last of human freedoms: choose attitude",
    "Happiness cannot be pursued; it ensues",
    "Between stimulus and response is freedom",
    "Each man is questioned by life"
    ];
